// Reference lists from the Luw.ai docs that have no API endpoint.
// Design styles, video styles and materials are fetched live instead.

export const INTERIOR_TYPES = [
  "Living Room",
  "Kitchen",
  "Bedroom",
  "Bathroom",
  "Attic",
  "Dining Room",
  "Study Room",
  "Home Office",
  "Gaming Room",
  "Meeting Room",
  "Workshop",
  "Fitness Gym",
  "Coffee Shop",
  "Clothing Store",
  "Walk-in Closet",
  "Toilet",
  "Restaurant",
  "Office",
  "Coworking Space",
  "Hotel Lobby",
  "Hotel Room",
  "Hotel Bathroom",
  "Exhibition Space",
  "Onsen",
  "Mudroom",
  "Open Kitchen",
  "Master Bedroom",
  "Kids Bedroom",
  "Laundry Room",
  "Home Theater",
  "Balcony",
  "Reception Area",
  "Cafe",
  "Retail Store",
  "Beauty Salon",
];

export const EXTERIOR_TYPES = [
  "House Exterior",
  "Outdoor Pool Area",
  "Outdoor Patio",
  "Outdoor Garden",
  "Modern House Exterior",
  "Traditional House Exterior",
  "Eco-Friendly House",
  "Sustainable Building",
  "Green Building Design",
  "Luxury Villa Exterior",
  "Apartment Complex",
  "Shopping Mall Exterior",
  "Skyscraper Building",
  "Hotel Building",
  "Office Building",
  "Cultural Center",
  "Museum Building",
  "Educational Building",
  "Hospital Building",
  "Sports Complex",
  "Transport Hub",
  "Mixed-Use Development",
  "Industrial Building",
  "Urban Residence",
  "Resort Complex",
  "Solar Powered House",
  "Container Building",
  "Bamboo Architecture",
  "Earth House",
  "Fitness Gym",
  "Coffee Shop",
  "Clothing Store",
  "Restaurant",
  "Exhibition Space",
  "Balcony",
  "Cafe",
  "Retail Store",
  "Beauty Salon",
];

export const PROFESSIONS = [
  "Interior",
  "Exterior",
  "Sketch",
  "Render",
  "MagicPrompt",
  "MagicWand",
  "Landscape",
  "Enhance",
  "Expand",
  "RemoveFurniture",
  "Vector",
  "ChangeBG",
  "Fluw",
  "Pattern",
  "MoodBoard",
  "Video",
  "3DGen",
  "ArchiGPT",
] as const;

/** Model ids accepted by POST /generate, for luw_run_model. */
export const MODEL_IDS = [
  "interior",
  "exterior",
  "sketch",
  "render",
  "magicprompt",
  "magicwand",
  "moodboard",
  "landscape",
  "enhance",
  "expand",
  "vector",
  "removefurniture",
  "segment",
  "segmentprompt",
  "fluw",
  "fluwvector",
  "pattern",
  "changebg",
  "removebg",
  "video",
  "3dgen",
];
